export type FieldType = 'text' | 'number' | 'email' | 'textarea' | 'date' | 'select' | 'relation' | 'lines';

export type Field = {
  name: string;
  label: string;
  type?: FieldType;
  required?: boolean;
  placeholder?: string;
  options?: { value: string; label: string }[];
  from?: string;
  labelKey?: string;
  valueKey?: string;
};

export type Column = { key: string; label: string };

export type ModuleDef = {
  slug: string;
  title: string;
  singular: string;
  group: 'sales' | 'inventory' | 'people' | 'service' | 'finance' | 'work' | 'setup';
  kicker: string;
  path: string;
  columns: Column[];
  fields: Field[];
  createable?: boolean;
  editable?: boolean;
  deletable?: boolean;
  createPath?: string;
  subtitle?: string;
  actions?: { label: string; path: (id: string) => string; method?: string; body?: Record<string, unknown> }[];
};

export const GROUPS: { id: ModuleDef['group']; label: string }[] = [
  { id: 'sales', label: 'Sales' },
  { id: 'inventory', label: 'Inventory' },
  { id: 'people', label: 'People' },
  { id: 'service', label: 'Service' },
  { id: 'finance', label: 'Finance' },
  { id: 'work', label: 'Work' },
  { id: 'setup', label: 'Setup' },
];

export const MODULES: ModuleDef[] = [
  {
    slug: 'leads',
    title: 'Leads',
    singular: 'Lead',
    group: 'sales',
    kicker: 'SAL-001',
    path: '/leads',
    subtitle: 'Inbound enquiries before they become customers.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'company', label: 'Company' },
      { key: 'source', label: 'Source' },
      { key: 'status', label: 'Status' },
      { key: 'value', label: 'Value' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'company', label: 'Company' },
      { name: 'phone', label: 'Phone' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'source', label: 'Source', required: true },
      { name: 'value', label: 'Value', type: 'number' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
    createable: true,
    editable: true,
    deletable: true,
    actions: [{ label: 'Convert to customer', path: (id) => `/leads/${id}/convert` }],
  },
  {
    slug: 'customers',
    title: 'Customers',
    singular: 'Customer',
    group: 'sales',
    kicker: 'SAL-003',
    path: '/customers',
    subtitle: 'Parties, credit limits and contact details.',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'creditLimit', label: 'Credit' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'legalName', label: 'Legal name' },
      { name: 'phone', label: 'Phone' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'taxId', label: 'Tax ID' },
      { name: 'creditLimit', label: 'Credit limit', type: 'number' },
      { name: 'paymentTermsDays', label: 'Payment terms (days)', type: 'number' },
      { name: 'billingAddress', label: 'Billing address', type: 'textarea' },
      { name: 'shippingAddress', label: 'Shipping address', type: 'textarea' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'vendors',
    title: 'Vendors',
    singular: 'Vendor',
    group: 'sales',
    kicker: 'SAL-003',
    path: '/vendors',
    subtitle: 'Suppliers used on purchase orders.',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'phone', label: 'Phone' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'taxId', label: 'Tax ID' },
      { name: 'creditLimit', label: 'Credit limit', type: 'number' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'opportunities',
    title: 'Opportunities',
    singular: 'Opportunity',
    group: 'sales',
    kicker: 'SAL-002',
    path: '/opportunities',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'party', label: 'Customer' },
      { key: 'stage', label: 'Stage' },
      { key: 'value', label: 'Value' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'partyId', label: 'Customer', type: 'relation', from: '/customers', required: true },
      { name: 'value', label: 'Value', type: 'number' },
      { name: 'probability', label: 'Probability %', type: 'number' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'quotations',
    title: 'Quotations',
    singular: 'Quotation',
    group: 'sales',
    kicker: 'SAL-004',
    path: '/quotations',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'party', label: 'Customer' },
      { key: 'status', label: 'Status' },
      { key: 'total', label: 'Total' },
    ],
    fields: [
      { name: 'partyId', label: 'Customer', type: 'relation', from: '/customers', required: true },
      { name: 'productId', label: 'Product', type: 'relation', from: '/products', required: true },
      { name: 'qty', label: 'Quantity', type: 'number', required: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
    createable: true,
    editable: true,
    actions: [
      { label: 'Approve', path: (id) => `/quotations/${id}/approve` },
      { label: 'Convert to order', path: (id) => `/quotations/${id}/convert` },
    ],
  },
  {
    slug: 'sales-orders',
    title: 'Sales orders',
    singular: 'Sales order',
    group: 'sales',
    kicker: 'SAL-005',
    path: '/sales-orders',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'party', label: 'Customer' },
      { key: 'status', label: 'Status' },
      { key: 'total', label: 'Total' },
    ],
    fields: [
      { name: 'partyId', label: 'Customer', type: 'relation', from: '/customers', required: true },
      { name: 'productId', label: 'Product', type: 'relation', from: '/products', required: true },
      { name: 'qty', label: 'Quantity', type: 'number', required: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
    createable: true,
    editable: true,
    actions: [
      { label: 'Approve / reserve', path: (id) => `/sales-orders/${id}/approve` },
      { label: 'Create invoice', path: (id) => `/sales-orders/${id}/invoice` },
    ],
  },
  {
    slug: 'invoices',
    title: 'Invoices',
    singular: 'Invoice',
    group: 'sales',
    kicker: 'ACC-002',
    path: '/invoices',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'party', label: 'Customer' },
      { key: 'status', label: 'Status' },
      { key: 'total', label: 'Total' },
      { key: 'paidAmount', label: 'Paid' },
    ],
    fields: [
      { name: 'notes', label: 'Notes', type: 'textarea' },
      { name: 'dueDate', label: 'Due date', type: 'date' },
    ],
    editable: true,
    actions: [{ label: 'Post invoice', path: (id) => `/invoices/${id}/post` }],
  },
  {
    slug: 'payments',
    title: 'Payments',
    singular: 'Payment',
    group: 'sales',
    kicker: 'ACC-005',
    path: '/payments',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'party', label: 'Customer' },
      { key: 'amount', label: 'Amount' },
      { key: 'method', label: 'Method' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'partyId', label: 'Customer', type: 'relation', from: '/customers', required: true },
      { name: 'invoiceId', label: 'Invoice', type: 'relation', from: '/invoices', labelKey: 'number', required: true },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'method', label: 'Method', type: 'select', options: [
        { value: 'BANK', label: 'Bank' },
        { value: 'CASH', label: 'Cash' },
        { value: 'UPI', label: 'UPI' },
      ] },
      { name: 'reference', label: 'Reference' },
    ],
    createable: true,
    editable: true,
    actions: [{ label: 'Approve', path: (id) => `/payments/${id}/approve` }],
  },
  {
    slug: 'products',
    title: 'Products',
    singular: 'Product',
    group: 'inventory',
    kicker: 'INV-001',
    path: '/products',
    columns: [
      { key: 'sku', label: 'SKU' },
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type' },
      { key: 'unitPrice', label: 'Price' },
      { key: 'taxRate', label: 'Tax %' },
    ],
    fields: [
      { name: 'sku', label: 'SKU', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'type', label: 'Type', type: 'select', options: [
        { value: 'GOODS', label: 'Goods' },
        { value: 'SERVICE', label: 'Service' },
      ] },
      { name: 'unitPrice', label: 'Unit price', type: 'number' },
      { name: 'costPrice', label: 'Cost price', type: 'number' },
      { name: 'taxRate', label: 'Tax %', type: 'number' },
      { name: 'reorderLevel', label: 'Reorder level', type: 'number' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'stock',
    title: 'Stock',
    singular: 'Stock balance',
    group: 'inventory',
    kicker: 'INV-002',
    path: '/stock',
    columns: [
      { key: 'product', label: 'Product' },
      { key: 'warehouse', label: 'Warehouse' },
      { key: 'onHand', label: 'On hand' },
      { key: 'reserved', label: 'Reserved' },
    ],
    fields: [],
    deletable: false,
  },
  {
    slug: 'warehouses',
    title: 'Warehouses',
    singular: 'Warehouse',
    group: 'inventory',
    kicker: 'INV-002',
    path: '/warehouses',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'isDefault', label: 'Default' },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Name', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'purchase-orders',
    title: 'Purchase orders',
    singular: 'Purchase order',
    group: 'inventory',
    kicker: 'INV-006',
    path: '/purchase-orders',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'party', label: 'Vendor' },
      { key: 'status', label: 'Status' },
      { key: 'total', label: 'Total' },
    ],
    fields: [
      { name: 'partyId', label: 'Supplier', type: 'relation', from: '/customers', required: true },
      { name: 'productId', label: 'Product', type: 'relation', from: '/products', required: true },
      { name: 'qty', label: 'Quantity', type: 'number', required: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
    createable: true,
    editable: true,
    actions: [{ label: 'Approve', path: (id) => `/purchase-orders/${id}/approve` }],
  },
  {
    slug: 'employees',
    title: 'Employees',
    singular: 'Employee',
    group: 'people',
    kicker: 'HR-001',
    path: '/employees',
    subtitle: 'Master records, bank details and shift assignment.',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'status', label: 'Status' },
      { key: 'designation', label: 'Designation' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'code', label: 'Code' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone' },
      { name: 'designationId', label: 'Designation', type: 'relation', from: '/designations' },
      { name: 'shiftId', label: 'Shift', type: 'relation', from: '/shifts' },
      { name: 'departmentId', label: 'Department', type: 'relation', from: '/departments' },
      { name: 'joiningDate', label: 'Joining date', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: [
        { value: 'ACTIVE', label: 'Active' },
        { value: 'ON_LEAVE', label: 'On leave' },
        { value: 'TERMINATED', label: 'Terminated' },
      ] },
      { name: 'bankAccount', label: 'Bank account' },
      { name: 'ifsc', label: 'IFSC' },
      { name: 'pan', label: 'PAN' },
      { name: 'emergencyName', label: 'Emergency contact' },
      { name: 'emergencyPhone', label: 'Emergency phone' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'designations',
    title: 'Designations',
    singular: 'Designation',
    group: 'people',
    kicker: 'HR-001',
    path: '/designations',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Name', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'shifts',
    title: 'Shifts',
    singular: 'Shift',
    group: 'people',
    kicker: 'HR-003',
    path: '/shifts',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'startTime', label: 'Start' },
      { key: 'endTime', label: 'End' },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'startTime', label: 'Start time', placeholder: '09:30', required: true },
      { name: 'endTime', label: 'End time', placeholder: '18:30', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'holidays',
    title: 'Holidays',
    singular: 'Holiday',
    group: 'people',
    kicker: 'HR-003',
    path: '/holidays',
    subtitle: 'Paid holidays used by attendance and payroll.',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'date', label: 'Date' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'date', label: 'Date', type: 'date', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'attendance',
    title: 'Attendance',
    singular: 'Attendance',
    group: 'people',
    kicker: 'HR-003',
    path: '/attendance',
    columns: [
      { key: 'workDate', label: 'Date' },
      { key: 'employee', label: 'Employee' },
      { key: 'status', label: 'Status' },
      { key: 'clockInAt', label: 'In' },
      { key: 'clockOutAt', label: 'Out' },
    ],
    fields: [
      { name: 'status', label: 'Status', type: 'select', options: [
        { value: 'PRESENT', label: 'Present' },
        { value: 'LATE', label: 'Late' },
        { value: 'ABSENT', label: 'Absent' },
        { value: 'HALF_DAY', label: 'Half day' },
      ] },
    ],
    editable: true,
  },
  {
    slug: 'leave-policies',
    title: 'Leave policies',
    singular: 'Leave policy',
    group: 'people',
    kicker: 'HR-004',
    path: '/leave-policies',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'annualDays', label: 'Days' },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'annualDays', label: 'Annual days', type: 'number', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'leave-requests',
    title: 'Leave requests',
    singular: 'Leave request',
    group: 'people',
    kicker: 'HR-004',
    path: '/leave-requests',
    columns: [
      { key: 'employee', label: 'Employee' },
      { key: 'policy', label: 'Policy' },
      { key: 'fromDate', label: 'From' },
      { key: 'toDate', label: 'To' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'employeeId', label: 'Employee', type: 'relation', from: '/employees', required: true },
      { name: 'policyId', label: 'Policy', type: 'relation', from: '/leave-policies', required: true },
      { name: 'fromDate', label: 'From', type: 'date', required: true },
      { name: 'toDate', label: 'To', type: 'date', required: true },
      { name: 'reason', label: 'Reason', type: 'textarea' },
    ],
    createable: true,
    editable: true,
    deletable: true,
    actions: [
      { label: 'Approve', path: (id) => `/leave-requests/${id}/decide`, body: { status: 'APPROVED' } },
      { label: 'Reject', path: (id) => `/leave-requests/${id}/decide`, body: { status: 'REJECTED' } },
    ],
  },
  {
    slug: 'salary-structures',
    title: 'Salary structures',
    singular: 'Salary structure',
    group: 'people',
    kicker: 'HR-005',
    path: '/salary-structures',
    subtitle: 'Earnings and deductions used when payroll is previewed.',
    columns: [
      { key: 'employee', label: 'Employee' },
      { key: 'effectiveFrom', label: 'Effective from' },
    ],
    fields: [
      { name: 'employeeId', label: 'Employee', type: 'relation', from: '/employees', required: true },
      { name: 'effectiveFrom', label: 'Effective from', type: 'date', required: true },
      { name: 'basic', label: 'Basic', type: 'number', required: true },
      { name: 'hra', label: 'HRA', type: 'number' },
      { name: 'deduction', label: 'PF / deduction', type: 'number' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'payroll-runs',
    title: 'Payroll',
    singular: 'Payroll run',
    group: 'people',
    kicker: 'HR-007',
    path: '/payroll-runs',
    createPath: '/payroll-runs/preview',
    columns: [
      { key: 'status', label: 'Status' },
      { key: 'periodStart', label: 'From' },
      { key: 'periodEnd', label: 'To' },
      { key: 'workingDays', label: 'Days' },
    ],
    fields: [
      { name: 'periodStart', label: 'Period start', type: 'date', required: true },
      { name: 'periodEnd', label: 'Period end', type: 'date', required: true },
      { name: 'workingDays', label: 'Working days', type: 'number' },
    ],
    createable: true,
    actions: [
      { label: 'Approve', path: (id) => `/payroll-runs/${id}/approve` },
      { label: 'Lock & post', path: (id) => `/payroll-runs/${id}/lock` },
      { label: 'Publish payslips', path: (id) => `/payroll-runs/${id}/publish` },
    ],
  },
  {
    slug: 'incentive-schemes',
    title: 'Incentive schemes',
    singular: 'Scheme',
    group: 'people',
    kicker: 'INC-001',
    path: '/incentive-schemes',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'formula', label: 'Formula' },
      { key: 'rate', label: 'Rate' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'formula', label: 'Formula', type: 'select', options: [
        { value: 'PERCENTAGE', label: 'Percentage' },
        { value: 'FIXED', label: 'Fixed' },
        { value: 'TARGET', label: 'Target' },
      ], required: true },
      { name: 'rate', label: 'Rate', type: 'number', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'incentive-awards',
    title: 'Incentive awards',
    singular: 'Award',
    group: 'people',
    kicker: 'INC-002',
    path: '/incentive-awards',
    columns: [
      { key: 'employee', label: 'Employee' },
      { key: 'scheme', label: 'Scheme' },
      { key: 'amount', label: 'Amount' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'schemeId', label: 'Scheme', type: 'relation', from: '/incentive-schemes', required: true },
      { name: 'periodStart', label: 'Period start', type: 'date', required: true },
      { name: 'periodEnd', label: 'Period end', type: 'date', required: true },
    ],
    createable: true,
    editable: true,
    createPath: '/incentive-awards/calculate',
    actions: [
      { label: 'Approve', path: (id) => `/incentive-awards/${id}/approve` },
      { label: 'Reverse', path: (id) => `/incentive-awards/${id}/reverse` },
    ],
  },
  {
    slug: 'service-tickets',
    title: 'Service tickets',
    singular: 'Ticket',
    group: 'service',
    kicker: 'RMA-001',
    path: '/service-tickets',
    subtitle: 'Intake, diagnosis, parts, QC and return to customer.',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'complaint', label: 'Complaint' },
      { key: 'status', label: 'Status' },
      { key: 'priority', label: 'Priority' },
      { key: 'technician', label: 'Allotted to' },
    ],
    fields: [
      { name: 'partyId', label: 'Customer', type: 'relation', from: '/customers', required: true },
      { name: 'productId', label: 'Product', type: 'relation', from: '/products' },
      { name: 'serialNo', label: 'Serial no.' },
      { name: 'complaint', label: 'Complaint', type: 'textarea', required: true },
      { name: 'technicianId', label: 'Allot employee', type: 'relation', from: '/employees' },
      { name: 'path', label: 'Service path', type: 'select', options: [
        { value: 'PAID_REPAIR', label: 'Paid repair' },
        { value: 'WARRANTY', label: 'Warranty' },
        { value: 'REPLACEMENT', label: 'Replacement' },
        { value: 'REFUND', label: 'Refund' },
        { value: 'VENDOR_RMA', label: 'Vendor RMA' },
      ] },
      { name: 'priority', label: 'Priority', type: 'select', options: [
        { value: 'LOW', label: 'Low' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'HIGH', label: 'High' },
      ] },
    ],
    createable: true,
    editable: true,
    deletable: true,
    actions: [],
  },
  {
    slug: 'pick-lists',
    title: 'Pick lists',
    singular: 'Pick list',
    group: 'service',
    kicker: 'DSP-001',
    path: '/pick-lists',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'salesOrderId', label: 'Sales order', type: 'relation', from: '/sales-orders', labelKey: 'number' },
      { name: 'ticketId', label: 'Ticket', type: 'relation', from: '/service-tickets', labelKey: 'number' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'shipments',
    title: 'Shipments',
    singular: 'Shipment',
    group: 'service',
    kicker: 'DSP-003',
    path: '/shipments',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'courier', label: 'Courier' },
      { key: 'awb', label: 'AWB' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'pickListId', label: 'Pick list', type: 'relation', from: '/pick-lists', labelKey: 'number' },
      { name: 'ticketId', label: 'Ticket', type: 'relation', from: '/service-tickets', labelKey: 'number' },
      { name: 'courier', label: 'Courier' },
      { name: 'freight', label: 'Freight', type: 'number' },
    ],
    createable: true,
    editable: true,
    deletable: true,
    actions: [
      { label: 'Pack', path: (id) => `/shipments/${id}/pack` },
      { label: 'Ship', path: (id) => `/shipments/${id}/ship`, body: { status: 'SHIPPED', awb: 'AWB-NEW' } },
      { label: 'Deliver', path: (id) => `/shipments/${id}/deliver` },
    ],
  },
  {
    slug: 'ledger-accounts',
    title: 'Chart of accounts',
    singular: 'Account',
    group: 'finance',
    kicker: 'ACC-001',
    path: '/ledger-accounts',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'type', label: 'Type' },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'type', label: 'Type', type: 'select', required: true, options: [
        { value: 'ASSET', label: 'Asset' },
        { value: 'LIABILITY', label: 'Liability' },
        { value: 'EQUITY', label: 'Equity' },
        { value: 'INCOME', label: 'Income' },
        { value: 'EXPENSE', label: 'Expense' },
      ] },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'vouchers',
    title: 'Journals',
    singular: 'Voucher',
    group: 'finance',
    kicker: 'ACC-003',
    path: '/vouchers',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'type', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'narration', label: 'Narration' },
    ],
    fields: [{ name: 'narration', label: 'Narration', type: 'textarea' }],
    editable: true,
    actions: [{ label: 'Reverse', path: (id) => `/vouchers/${id}/reverse` }],
  },
  {
    slug: 'recurring-schedules',
    title: 'Recurring schedules',
    singular: 'Schedule',
    group: 'finance',
    kicker: 'REC-001',
    path: '/recurring-schedules',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'kind', label: 'Kind' },
      { key: 'frequency', label: 'Frequency' },
      { key: 'amount', label: 'Amount' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'kind', label: 'Kind', type: 'select', required: true, options: [
        { value: 'AMC', label: 'AMC' },
        { value: 'RENT', label: 'Rent' },
        { value: 'SALARY', label: 'Salary' },
        { value: 'SUBSCRIPTION', label: 'Subscription' },
      ] },
      { name: 'frequency', label: 'Frequency', type: 'select', required: true, options: [
        { value: 'MONTHLY', label: 'Monthly' },
        { value: 'WEEKLY', label: 'Weekly' },
        { value: 'ANNUAL', label: 'Annual' },
      ] },
      { name: 'partyId', label: 'Customer', type: 'relation', from: '/customers' },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'taxRate', label: 'Tax %', type: 'number' },
      { name: 'nextRunAt', label: 'Next run', type: 'date', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
    actions: [{ label: 'Run due now', path: () => '/recurring-schedules/run' }],
  },
  {
    slug: 'bank-accounts',
    title: 'Bank accounts',
    singular: 'Bank account',
    group: 'finance',
    kicker: 'BNK-001',
    path: '/bank-accounts',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'maskedNumber', label: 'Number' },
      { key: 'provider', label: 'Provider' },
    ],
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'maskedNumber', label: 'Masked number', required: true },
      { name: 'provider', label: 'Provider' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'bank-transactions',
    title: 'Bank transactions',
    singular: 'Bank transaction',
    group: 'finance',
    kicker: 'BNK-002',
    path: '/bank-transactions',
    columns: [
      { key: 'txnDate', label: 'Date' },
      { key: 'description', label: 'Description' },
      { key: 'amount', label: 'Amount' },
      { key: 'matchStatus', label: 'Match' },
    ],
    fields: [{ name: 'description', label: 'Description', type: 'textarea' }],
    editable: true,
    actions: [{ label: 'Confirm match', path: (id) => `/bank-transactions/${id}/confirm` }],
  },
  {
    slug: 'tasks',
    title: 'Tasks',
    singular: 'Task',
    group: 'work',
    kicker: 'TSK-001',
    path: '/tasks',
    columns: [
      { key: 'number', label: 'No.' },
      { key: 'title', label: 'Title' },
      { key: 'status', label: 'Status' },
      { key: 'priority', label: 'Priority' },
    ],
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'priority', label: 'Priority', type: 'select', options: [
        { value: 'LOW', label: 'Low' },
        { value: 'NORMAL', label: 'Normal' },
        { value: 'HIGH', label: 'High' },
      ] },
      { name: 'employeeId', label: 'Allot employee', type: 'relation', from: '/employees' },
      { name: 'departmentId', label: 'Department', type: 'relation', from: '/departments' },
      { name: 'dueAt', label: 'Due date', type: 'date' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'conversations',
    title: 'WhatsApp',
    singular: 'Conversation',
    group: 'work',
    kicker: 'WAP-001',
    path: '/conversations',
    columns: [
      { key: 'status', label: 'Status' },
      { key: 'optOut', label: 'Opt out' },
      { key: 'channel', label: 'Channel' },
    ],
    fields: [
      { name: 'status', label: 'Status', type: 'select', options: [
        { value: 'OPEN', label: 'Open' },
        { value: 'ASSIGNED', label: 'Assigned' },
        { value: 'CLOSED', label: 'Closed' },
      ] },
    ],
    editable: true,
    actions: [{ label: 'Assign to me', path: (id) => `/conversations/${id}/assign` }],
  },
  {
    slug: 'channels',
    title: 'Channels',
    singular: 'Channel',
    group: 'work',
    kicker: 'WAP-001',
    path: '/channels',
    columns: [
      { key: 'provider', label: 'Provider' },
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone' },
    ],
    fields: [
      { name: 'provider', label: 'Provider', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'phone', label: 'Phone' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'marketplace-listings',
    title: 'Marketplace listings',
    singular: 'Listing',
    group: 'work',
    kicker: 'MKT-001',
    path: '/marketplace-listings',
    columns: [
      { key: 'channel', label: 'Channel' },
      { key: 'listingId', label: 'Listing' },
      { key: 'version', label: 'Version' },
    ],
    fields: [
      { name: 'channel', label: 'Channel', required: true },
      { name: 'productId', label: 'Product', type: 'relation', from: '/products', required: true },
      { name: 'listingId', label: 'Listing ID', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'marketplace-orders',
    title: 'Marketplace orders',
    singular: 'Marketplace order',
    group: 'work',
    kicker: 'MKT-002',
    path: '/marketplace-orders',
    columns: [
      { key: 'channel', label: 'Channel' },
      { key: 'externalId', label: 'External ID' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'channel', label: 'Channel', required: true },
      { name: 'externalId', label: 'External ID', required: true },
    ],
    createable: true,
    editable: true,
  },
  {
    slug: 'imports',
    title: 'Imports',
    singular: 'Import batch',
    group: 'setup',
    kicker: 'MIG-001',
    path: '/imports',
    columns: [
      { key: 'sourceSystem', label: 'Source' },
      { key: 'entityType', label: 'Entity' },
      { key: 'status', label: 'Status' },
      { key: 'dryRun', label: 'Dry run' },
    ],
    fields: [
      { name: 'sourceSystem', label: 'Source system', required: true },
      { name: 'entityType', label: 'Entity type', type: 'select', required: true, options: [
        { value: 'customers', label: 'Customers' },
        { value: 'products', label: 'Products' },
        { value: 'employees', label: 'Employees' },
      ] },
    ],
    createable: false,
    actions: [
      { label: 'Commit', path: (id) => `/imports/${id}/commit` },
      { label: 'Rollback', path: (id) => `/imports/${id}/rollback` },
    ],
  },
  {
    slug: 'branches',
    title: 'Branches',
    singular: 'Branch',
    group: 'setup',
    kicker: 'ADM-001',
    path: '/branches',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
      { key: 'isDefault', label: 'Default' },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Name', required: true },
      { name: 'timezone', label: 'Timezone' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'departments',
    title: 'Departments',
    singular: 'Department',
    group: 'setup',
    kicker: 'ADM-001',
    path: '/departments',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Name' },
    ],
    fields: [
      { name: 'code', label: 'Code', required: true },
      { name: 'name', label: 'Name', required: true },
    ],
    createable: true,
    editable: true,
    deletable: true,
  },
  {
    slug: 'roles',
    title: 'Roles',
    singular: 'Role',
    group: 'setup',
    kicker: 'RBAC',
    path: '/roles',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'code', label: 'Code' },
      { key: 'isSystem', label: 'System' },
    ],
    fields: [],
  },
  {
    slug: 'sequences',
    title: 'Numbering',
    singular: 'Sequence',
    group: 'setup',
    kicker: 'ADM-003',
    path: '/sequences',
    columns: [
      { key: 'documentType', label: 'Type' },
      { key: 'prefix', label: 'Prefix' },
      { key: 'nextNumber', label: 'Next' },
    ],
    fields: [
      { name: 'prefix', label: 'Prefix' },
      { name: 'nextNumber', label: 'Next number', type: 'number' },
      { name: 'padding', label: 'Padding', type: 'number' },
    ],
    editable: true,
  },
  {
    slug: 'settings',
    title: 'Settings',
    singular: 'Setting',
    group: 'setup',
    kicker: 'TEN-006',
    path: '/settings',
    columns: [
      { key: 'key', label: 'Key' },
      { key: 'value', label: 'Value' },
    ],
    fields: [],
    editable: true,
  },
  {
    slug: 'fiscal-years',
    title: 'Fiscal years',
    singular: 'Fiscal year',
    group: 'setup',
    kicker: 'ACC-001',
    path: '/fiscal-years',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'isCurrent', label: 'Current' },
      { key: 'isLocked', label: 'Locked' },
    ],
    fields: [{ name: 'name', label: 'Name' }],
    editable: true,
  },
  {
    slug: 'notifications',
    title: 'Inbox',
    singular: 'Notification',
    group: 'setup',
    kicker: 'ADM-006',
    path: '/notifications',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'body', label: 'Body' },
      { key: 'createdAt', label: 'When' },
    ],
    fields: [],
  },
  {
    slug: 'audit-events',
    title: 'Audit trail',
    singular: 'Audit event',
    group: 'setup',
    kicker: 'ADM-005',
    path: '/audit-events',
    columns: [
      { key: 'action', label: 'Action' },
      { key: 'entityType', label: 'Entity' },
      { key: 'createdAt', label: 'When' },
    ],
    fields: [],
  },
];

export function moduleBySlug(slug: string) {
  return MODULES.find((item) => item.slug === slug);
}

export function canDelete(mod: ModuleDef) {
  if (mod.deletable === false) {
    return false;
  }
  return !['stock', 'notifications', 'audit-events'].includes(mod.slug);
}
