export const PERMISSION_CATALOG = [
  ['tenants', 'view', 'View tenants'],
  ['tenants', 'create', 'Create tenants'],
  ['tenants', 'edit', 'Edit tenants'],
  ['tenants', 'administer', 'Administer tenants'],
  ['branches', 'view', 'View branches'],
  ['branches', 'create', 'Create branches'],
  ['branches', 'edit', 'Edit branches'],
  ['branches', 'administer', 'Administer branches'],
  ['departments', 'view', 'View departments'],
  ['departments', 'create', 'Create departments'],
  ['departments', 'edit', 'Edit departments'],
  ['users', 'view', 'View users'],
  ['users', 'create', 'Invite users'],
  ['users', 'edit', 'Edit users'],
  ['users', 'administer', 'Administer users'],
  ['roles', 'view', 'View roles'],
  ['roles', 'edit', 'Edit roles'],
  ['roles', 'administer', 'Administer roles'],
  ['settings', 'view', 'View settings'],
  ['settings', 'edit', 'Edit settings'],
  ['settings', 'administer', 'Administer settings'],
  ['sequences', 'view', 'View document sequences'],
  ['sequences', 'edit', 'Edit document sequences'],
  ['fiscal-years', 'view', 'View fiscal years'],
  ['fiscal-years', 'create', 'Create fiscal years'],
  ['fiscal-years', 'edit', 'Edit fiscal years'],
  ['audit', 'view', 'View audit trail'],
  ['audit', 'export', 'Export audit trail'],
  ['notifications', 'view', 'View notifications'],
  ['notifications', 'administer', 'Administer notifications'],
  ['approvals', 'view', 'View approval policies'],
  ['approvals', 'approve', 'Approve requests'],
  ['approvals', 'administer', 'Administer approval policies'],
  ['reports', 'view', 'View reports'],
  ['reports', 'export', 'Export reports'],
  ['tasks', 'view', 'View tasks'],
  ['tasks', 'create', 'Create tasks'],
  ['tasks', 'edit', 'Edit tasks'],
  ['leads', 'view', 'View leads'],
  ['leads', 'create', 'Create leads'],
  ['leads', 'edit', 'Edit leads'],
  ['customers', 'view', 'View customers'],
  ['customers', 'create', 'Create customers'],
  ['customers', 'edit', 'Edit customers'],
  ['opportunities', 'view', 'View opportunities'],
  ['opportunities', 'create', 'Create opportunities'],
  ['opportunities', 'edit', 'Edit opportunities'],
  ['quotations', 'view', 'View quotations'],
  ['quotations', 'create', 'Create quotations'],
  ['quotations', 'edit', 'Edit quotations'],
  ['quotations', 'approve', 'Approve quotations'],
  ['sales-orders', 'view', 'View sales orders'],
  ['sales-orders', 'create', 'Create sales orders'],
  ['sales-orders', 'edit', 'Edit sales orders'],
  ['sales-orders', 'approve', 'Approve sales orders'],
  ['sales-orders', 'cancel', 'Cancel sales orders'],
  ['products', 'view', 'View products'],
  ['products', 'create', 'Create products'],
  ['products', 'edit', 'Edit products'],
  ['inventory', 'view', 'View inventory'],
  ['inventory', 'create', 'Record stock movements'],
  ['inventory', 'edit', 'Adjust inventory'],
  ['purchase-orders', 'view', 'View purchase orders'],
  ['purchase-orders', 'create', 'Create purchase orders'],
  ['purchase-orders', 'edit', 'Edit purchase orders'],
  ['purchase-orders', 'approve', 'Approve purchase orders'],
  ['invoices', 'view', 'View invoices'],
  ['invoices', 'create', 'Create invoices'],
  ['invoices', 'approve', 'Post invoices'],
  ['invoices', 'cancel', 'Cancel invoices'],
  ['payments', 'view', 'View payments'],
  ['payments', 'create', 'Create payments'],
  ['payments', 'approve', 'Approve payments'],
  ['accounts', 'view', 'View ledger accounts'],
  ['accounts', 'create', 'Create ledger accounts'],
  ['accounts', 'edit', 'Edit ledger accounts'],
  ['accounts', 'approve', 'Post journals'],
  ['employees', 'view', 'View employees'],
  ['employees', 'create', 'Create employees'],
  ['employees', 'edit', 'Edit employees'],
  ['attendance', 'view', 'View attendance'],
  ['attendance', 'create', 'Capture attendance'],
  ['attendance', 'approve', 'Approve attendance'],
  ['leave', 'view', 'View leave'],
  ['leave', 'create', 'Request leave'],
  ['leave', 'approve', 'Approve leave'],
  ['payroll', 'view', 'View payroll'],
  ['payroll', 'create', 'Create payroll runs'],
  ['payroll', 'approve', 'Approve payroll'],
  ['incentives', 'view', 'View incentives'],
  ['incentives', 'create', 'Create incentive schemes'],
  ['incentives', 'approve', 'Approve incentives'],
  ['service-tickets', 'view', 'View service tickets'],
  ['service-tickets', 'create', 'Create service tickets'],
  ['service-tickets', 'edit', 'Edit service tickets'],
  ['service-tickets', 'approve', 'Approve estimates and QC'],
  ['rma', 'view', 'View RMA'],
  ['rma', 'create', 'Create RMA'],
  ['rma', 'edit', 'Edit RMA'],
  ['dispatch', 'view', 'View dispatch'],
  ['dispatch', 'create', 'Create pick lists and shipments'],
  ['dispatch', 'edit', 'Update dispatch status'],
  ['recurring', 'view', 'View recurring schedules'],
  ['recurring', 'create', 'Create recurring schedules'],
  ['recurring', 'edit', 'Edit recurring schedules'],
  ['banking', 'view', 'View bank feeds'],
  ['banking', 'create', 'Import bank transactions'],
  ['banking', 'approve', 'Confirm reconciliation'],
  ['whatsapp', 'view', 'View WhatsApp conversations'],
  ['whatsapp', 'create', 'Send WhatsApp messages'],
  ['whatsapp', 'edit', 'Assign conversations'],
  ['marketplaces', 'view', 'View marketplace listings'],
  ['marketplaces', 'create', 'Import marketplace orders'],
  ['marketplaces', 'edit', 'Publish catalogue updates'],
  ['imports', 'view', 'View import batches'],
  ['imports', 'create', 'Run imports'],
  ['imports', 'administer', 'Rollback import batches'],
  ['recycle-bin', 'view', 'View company deleted records'],
  ['recycle-bin', 'administer', 'Restore company deleted records'],
] as const;

export type PermissionKey = `${(typeof PERMISSION_CATALOG)[number][0]}:${(typeof PERMISSION_CATALOG)[number][1]}`;

export const ROLE_TEMPLATES: Record<string, { name: string; description: string; permissions: string[] | '*' }> = {
  tenant_owner: {
    name: 'Tenant owner',
    description: 'All tenant branches, configuration, integrations and reports',
    permissions: '*',
  },
  department_manager: {
    name: 'Department manager',
    description: 'Team assignments, approvals, targets and departmental reports',
    permissions: [
      'branches:view',
      'departments:view',
      'users:view',
      'users:edit',
      'roles:view',
      'settings:view',
      'sequences:view',
      'fiscal-years:view',
      'audit:view',
      'recycle-bin:view',
      'recycle-bin:administer',
      'notifications:view',
      'approvals:view',
      'approvals:approve',
      'reports:view',
      'reports:export',
      'tasks:view',
      'tasks:create',
      'tasks:edit',
      'leads:view',
      'leads:edit',
      'customers:view',
      'opportunities:view',
      'quotations:view',
      'quotations:approve',
      'sales-orders:view',
      'sales-orders:approve',
      'products:view',
      'inventory:view',
      'invoices:view',
      'payments:view',
      'accounts:view',
      'employees:view',
      'attendance:view',
      'attendance:approve',
      'leave:view',
      'leave:approve',
      'payroll:view',
      'incentives:view',
      'incentives:approve',
      'service-tickets:view',
      'service-tickets:approve',
      'dispatch:view',
      'recurring:view',
      'banking:view',
    ],
  },
  sales_user: {
    name: 'Sales user',
    description: 'Leads, follow-ups, quotations, orders and permitted customer data',
    permissions: [
      'users:view',
      'branches:view',
      'notifications:view',
      'reports:view',
      'tasks:view',
      'tasks:create',
      'tasks:edit',
      'leads:view',
      'leads:create',
      'leads:edit',
      'customers:view',
      'customers:create',
      'customers:edit',
      'opportunities:view',
      'opportunities:create',
      'opportunities:edit',
      'quotations:view',
      'quotations:create',
      'quotations:edit',
      'quotations:approve',
      'sales-orders:view',
      'sales-orders:create',
      'sales-orders:edit',
      'sales-orders:approve',
      'products:view',
      'inventory:view',
      'invoices:view',
    ],
  },
  service_user: {
    name: 'Service user',
    description: 'Tickets, job sheets, RMA, parts and service statuses',
    permissions: [
      'users:view',
      'branches:view',
      'notifications:view',
      'tasks:view',
      'tasks:create',
      'tasks:edit',
      'customers:view',
      'products:view',
      'inventory:view',
      'service-tickets:view',
      'service-tickets:create',
      'service-tickets:edit',
      'rma:view',
      'rma:create',
      'rma:edit',
    ],
  },
  accounts_user: {
    name: 'Accounts user',
    description: 'Vouchers, ledgers, invoices, collections and payroll as permitted',
    permissions: [
      'users:view',
      'branches:view',
      'fiscal-years:view',
      'sequences:view',
      'notifications:view',
      'approvals:view',
      'approvals:approve',
      'reports:view',
      'reports:export',
      'audit:view',
      'customers:view',
      'products:view',
      'sales-orders:view',
      'invoices:view',
      'invoices:create',
      'invoices:approve',
      'payments:view',
      'payments:create',
      'payments:approve',
      'accounts:view',
      'accounts:create',
      'accounts:edit',
      'accounts:approve',
      'purchase-orders:view',
      'payroll:view',
      'payroll:create',
      'payroll:approve',
      'incentives:view',
      'incentives:approve',
      'employees:view',
      'banking:view',
      'banking:create',
      'banking:approve',
      'recurring:view',
      'recurring:create',
      'recurring:edit',
    ],
  },
  dispatch_user: {
    name: 'Dispatch user',
    description: 'Pick, pack, AWB, shipment, delivery and returns',
    permissions: [
      'users:view',
      'branches:view',
      'notifications:view',
      'products:view',
      'inventory:view',
      'sales-orders:view',
      'service-tickets:view',
      'dispatch:view',
      'dispatch:create',
      'dispatch:edit',
    ],
  },
  employee: {
    name: 'Employee',
    description: 'Own tasks, attendance, leave, payslips, incentives and notifications',
    permissions: [
      'notifications:view',
      'tasks:view',
      'tasks:create',
      'tasks:edit',
      'attendance:view',
      'attendance:create',
      'leave:view',
      'leave:create',
      'payroll:view',
      'incentives:view',
    ],
  },
  auditor: {
    name: 'Auditor',
    description: 'Read-only access to approved records, reports and audit trails',
    permissions: [
      'branches:view',
      'departments:view',
      'users:view',
      'roles:view',
      'settings:view',
      'sequences:view',
      'fiscal-years:view',
      'audit:view',
      'audit:export',
      'recycle-bin:view',
      'reports:view',
      'reports:export',
      'approvals:view',
      'tasks:view',
      'leads:view',
      'customers:view',
      'opportunities:view',
      'quotations:view',
      'sales-orders:view',
      'products:view',
      'inventory:view',
      'purchase-orders:view',
      'invoices:view',
      'payments:view',
      'accounts:view',
      'employees:view',
      'attendance:view',
      'leave:view',
      'payroll:view',
      'incentives:view',
      'service-tickets:view',
      'rma:view',
      'dispatch:view',
      'recurring:view',
      'banking:view',
      'whatsapp:view',
      'marketplaces:view',
      'imports:view',
    ],
  },
};
